version: "3.8"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD} 
    command: -p ${DB_PORT} 
  shop:
    build:
      context: "../../"
      dockerfile: "build/production/Dockerfile"
      args:
        MOD_NAME: "shop"
    environment:
      DB_IP: db
      DB_PORT: ${DB_PORT} 
      DB_USER: ${DB_USER} 
      DB_PASSWORD: ${DB_PASSWORD} 
      DB_NAME: "postgres"
    links:
      - db
    depends_on:
      - db
    ports:
      - "3333:3333"

